# kafka installation for capitalist
version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9090:9090"
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://kafka:9092,INTERNAL://kafka:9090
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL_SAME_HOST://localhost:9092,INTERNAL://kafka:9090
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181   
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 180000000 

networks:
  default:
    name: boltzman
    external: true



    